# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGNR95_QPGGsjl_L8aNyxXpwdDr9tsrE
"""

!pip install shap imbalanced-learn xgboost lightgbm --quiet

# Core
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Visualization
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
sns.set_theme(style='whitegrid', palette='Set2')

# Preprocessing
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Evaluation
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, ConfusionMatrixDisplay,
    classification_report, roc_curve, precision_recall_curve
)

# Explainability
import shap

print("✅ All libraries imported successfully!")

# ========================================================
# CELL 2: Load Dataset
# IBM HR Analytics Dataset — available on Kaggle & sklearn
# We load it directly via URL for Colab convenience
# ========================================================

url = "https://raw.githubusercontent.com/IBM/employee-attrition-aif360/master/data/emp_attrition.csv"

try:
    df = pd.read_csv(url)
    print("✅ Dataset loaded from GitHub")
except:
    # Fallback: create synthetic IBM-like dataset if network unavailable
    print("⚠️  Falling back to synthetic dataset...")
    from sklearn.datasets import make_classification
    np.random.seed(42)
    n = 1470
    df = pd.DataFrame({
        'Age': np.random.randint(18, 60, n),
        'Attrition': np.random.choice(['Yes','No'], n, p=[0.16, 0.84]),
        'BusinessTravel': np.random.choice(['Non-Travel','Travel_Rarely','Travel_Frequently'], n),
        'DailyRate': np.random.randint(100, 1500, n),
        'Department': np.random.choice(['Sales','R&D','HR'], n),
        'DistanceFromHome': np.random.randint(1, 30, n),
        'Education': np.random.randint(1, 5, n),
        'EducationField': np.random.choice(['Life Sciences','Medical','Marketing','Technical Degree','Other'], n),
        'EnvironmentSatisfaction': np.random.randint(1, 5, n),
        'Gender': np.random.choice(['Male','Female'], n),
        'HourlyRate': np.random.randint(30, 100, n),
        'JobInvolvement': np.random.randint(1, 5, n),
        'JobLevel': np.random.randint(1, 5, n),
        'JobRole': np.random.choice(['Sales Executive','Research Scientist','Lab Technician','Manager','HR'], n),
        'JobSatisfaction': np.random.randint(1, 5, n),
        'MaritalStatus': np.random.choice(['Single','Married','Divorced'], n),
        'MonthlyIncome': np.random.randint(1000, 20000, n),
        'MonthlyRate': np.random.randint(2000, 27000, n),
        'NumCompaniesWorked': np.random.randint(0, 10, n),
        'OverTime': np.random.choice(['Yes','No'], n),
        'PercentSalaryHike': np.random.randint(10, 25, n),
        'PerformanceRating': np.random.randint(3, 5, n),
        'RelationshipSatisfaction': np.random.randint(1, 5, n),
        'StockOptionLevel': np.random.randint(0, 4, n),
        'TotalWorkingYears': np.random.randint(0, 40, n),
        'TrainingTimesLastYear': np.random.randint(0, 6, n),
        'WorkLifeBalance': np.random.randint(1, 5, n),
        'YearsAtCompany': np.random.randint(0, 40, n),
        'YearsInCurrentRole': np.random.randint(0, 18, n),
        'YearsSinceLastPromotion': np.random.randint(0, 15, n),
        'YearsWithCurrManager': np.random.randint(0, 17, n),
    })

print(f"📊 Dataset shape: {df.shape}")
print(f"📋 Columns: {df.columns.tolist()}")
df.head()

# ========================================================
# CELL 3: Exploratory Data Analysis (EDA)
# ========================================================

print("=" * 60)
print("📊 BASIC DATA OVERVIEW")
print("=" * 60)
print(f"Shape       : {df.shape}")
print(f"Missing vals: {df.isnull().sum().sum()}")
print(f"Duplicates  : {df.duplicated().sum()}")
print()
print("Data Types:")
print(df.dtypes.value_counts())
print()
print("Attrition Distribution:")
print(df['Attrition'].value_counts())
print(f"\nAttrition Rate: {df['Attrition'].value_counts(normalize=True)['Yes']*100:.1f}%")

# ========================================================
# CELL 4: Target Variable Distribution
# ========================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Bar chart
counts = df['Attrition'].value_counts()
colors = ['#2ecc71', '#e74c3c']
axes[0].bar(counts.index, counts.values, color=colors, edgecolor='black', linewidth=1.2)
axes[0].set_title('Employee Attrition Count', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Attrition')
axes[0].set_ylabel('Count')
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 10, str(v), ha='center', fontweight='bold', fontsize=13)

# Pie chart
axes[1].pie(counts.values, labels=counts.index, autopct='%1.1f%%',
            colors=colors, startangle=90, explode=(0, 0.05),
            textprops={'fontsize': 13})
axes[1].set_title('Attrition Proportion', fontsize=14, fontweight='bold')

plt.suptitle('⚠️ Class Imbalance: Attrition = ~16% (Minority Class)',
             fontsize=13, color='darkred', y=1.02)
plt.tight_layout()
plt.savefig('attrition_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Class imbalance confirmed — will use SMOTE to handle this.")

# ========================================================
# CELL 5: Categorical Feature Analysis
# ========================================================

cat_features = ['Department', 'JobRole', 'MaritalStatus', 'OverTime', 'BusinessTravel', 'Gender']

# Filter to only columns that exist
cat_features = [c for c in cat_features if c in df.columns]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(cat_features):
    ct = pd.crosstab(df[col], df['Attrition'], normalize='index') * 100
    ct.plot(kind='bar', ax=axes[i], color=['#2ecc71','#e74c3c'],
            edgecolor='black', linewidth=0.8)
    axes[i].set_title(f'Attrition % by {col}', fontweight='bold')
    axes[i].set_ylabel('Percentage (%)')
    axes[i].set_xlabel('')
    axes[i].legend(['No Attrition', 'Attrition'], loc='upper right')
    axes[i].tick_params(axis='x', rotation=30)

plt.suptitle('Attrition Rate by Categorical Features', fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('categorical_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

# ========================================================
# CELL 6: Numerical Feature Analysis
# ========================================================

num_features = ['Age', 'MonthlyIncome', 'DistanceFromHome', 'TotalWorkingYears',
                'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion']
num_features = [c for c in num_features if c in df.columns]

fig, axes = plt.subplots(2, 4, figsize=(20, 10))
axes = axes.flatten()

for i, col in enumerate(num_features):
    yes = df[df['Attrition'] == 'Yes'][col]
    no  = df[df['Attrition'] == 'No'][col]
    axes[i].hist(no, bins=25, alpha=0.6, color='#2ecc71', label='No Attrition')
    axes[i].hist(yes, bins=25, alpha=0.6, color='#e74c3c', label='Attrition')
    axes[i].set_title(f'{col}', fontweight='bold')
    axes[i].legend(fontsize=9)

# Hide extra subplot
if len(num_features) < len(axes):
    for j in range(len(num_features), len(axes)):
        axes[j].set_visible(False)

plt.suptitle('Distribution of Numerical Features by Attrition', fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('numerical_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

# ========================================================
# CELL 7: Correlation Heatmap
# ========================================================

# Temporary encode for correlation
df_temp = df.copy()
df_temp['Attrition_bin'] = (df_temp['Attrition'] == 'Yes').astype(int)

num_cols = df_temp.select_dtypes(include=['int64','float64']).columns.tolist()

plt.figure(figsize=(14, 10))
corr = df_temp[num_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, linewidths=0.5, annot_kws={'size': 8})
plt.title('Correlation Heatmap of Numerical Features', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('correlation_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Top correlations with Attrition
if 'Attrition_bin' in corr.columns:
    print("\n📌 Top Features Correlated with Attrition:")
    print(corr['Attrition_bin'].drop('Attrition_bin').abs().sort_values(ascending=False).head(10))

# ========================================================
# CELL 8: Preprocessing Pipeline
# ========================================================

df_model = df.copy()

# Drop columns with no predictive value
cols_to_drop = ['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours']
df_model.drop(columns=[c for c in cols_to_drop if c in df_model.columns], inplace=True)

# Encode target
df_model['Attrition'] = (df_model['Attrition'] == 'Yes').astype(int)

# Encode binary categoricals
binary_map = {'Male': 1, 'Female': 0, 'Yes': 1, 'No': 0}
for col in ['Gender', 'OverTime']:
    if col in df_model.columns:
        df_model[col] = df_model[col].map(binary_map)

# One-Hot Encode remaining categoricals
cat_cols = df_model.select_dtypes(include='object').columns.tolist()
df_model = pd.get_dummies(df_model, columns=cat_cols, drop_first=True)

# Feature Engineering — new meaningful features
if 'YearsAtCompany' in df_model.columns and 'TotalWorkingYears' in df_model.columns:
    df_model['CompanyLoyaltyRatio'] = df_model['YearsAtCompany'] / (df_model['TotalWorkingYears'] + 1)

if 'YearsSinceLastPromotion' in df_model.columns and 'YearsAtCompany' in df_model.columns:
    df_model['PromotionGap'] = df_model['YearsSinceLastPromotion'] / (df_model['YearsAtCompany'] + 1)

print(f"✅ Preprocessed Shape: {df_model.shape}")
print(f"Features: {df_model.shape[1] - 1}")
print(f"Target distribution: {df_model['Attrition'].value_counts().to_dict()}")

# ========================================================
# CELL 9: Train-Test Split + SMOTE
# ========================================================

X = df_model.drop('Attrition', axis=1)
y = df_model['Attrition']

# Train-test split (stratified to preserve ratio)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train size: {X_train.shape}")
print(f"Test size : {X_test.shape}")
print(f"\nBefore SMOTE — Train target distribution:")
print(y_train.value_counts())

# Apply SMOTE on training set only
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

print(f"\nAfter SMOTE — Train target distribution:")
print(pd.Series(y_train_sm).value_counts())

# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_sm)
X_test_scaled  = scaler.transform(X_test)

print("\n✅ Data ready for modeling!")

# ========================================================
# CELL 10: Train Multiple Models
# ========================================================

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree':       DecisionTreeClassifier(max_depth=5, random_state=42),
    'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42),
    'XGBoost':             XGBClassifier(use_label_encoder=False, eval_metric='logloss',
                                         random_state=42, verbosity=0),
    'LightGBM':            LGBMClassifier(random_state=42, verbose=-1),
    'Gradient Boosting':   GradientBoostingClassifier(n_estimators=100, random_state=42),
}

results = {}

print("Training models...")
print("-" * 70)
print(f"{'Model':<22} {'Accuracy':>10} {'Precision':>10} {'Recall':>10} {'F1':>10} {'AUC':>10}")
print("-" * 70)

for name, model in models.items():
    # Use scaled data for LR and SVM, raw for tree-based
    if name in ['Logistic Regression']:
        model.fit(X_train_scaled, y_train_sm)
        y_pred = model.predict(X_test_scaled)
        y_prob = model.predict_proba(X_test_scaled)[:, 1]
    else:
        model.fit(X_train_sm, y_train_sm)
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

    acc   = accuracy_score(y_test, y_pred)
    prec  = precision_score(y_test, y_pred)
    rec   = recall_score(y_test, y_pred)
    f1    = f1_score(y_test, y_pred)
    auc   = roc_auc_score(y_test, y_prob)

    results[name] = {
        'model': model, 'y_pred': y_pred, 'y_prob': y_prob,
        'Accuracy': acc, 'Precision': prec,
        'Recall': rec, 'F1': f1, 'AUC-ROC': auc
    }

    print(f"{name:<22} {acc:>10.4f} {prec:>10.4f} {rec:>10.4f} {f1:>10.4f} {auc:>10.4f}")

print("-" * 70)
print("✅ All models trained!")

# ========================================================
# CELL 11: Comparison Bar Chart
# ========================================================

metrics = ['Accuracy', 'Precision', 'Recall', 'F1', 'AUC-ROC']
model_names = list(results.keys())
scores_df = pd.DataFrame({
    name: {m: results[name][m] for m in metrics} for name in model_names
}).T

ax = scores_df.plot(kind='bar', figsize=(14, 6), colormap='Set1', edgecolor='black')
ax.set_title('Model Comparison — All Metrics', fontsize=15, fontweight='bold')
ax.set_xlabel('Model')
ax.set_ylabel('Score')
ax.set_ylim(0, 1.1)
ax.legend(loc='lower right')
plt.xticks(rotation=25, ha='right')
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

# Best model by AUC
best_model_name = scores_df['AUC-ROC'].idxmax()
print(f"\n🏆 Best Model by AUC-ROC: {best_model_name} ({scores_df.loc[best_model_name, 'AUC-ROC']:.4f})")

# ========================================================
# CELL 12: ROC Curves — All Models
# ========================================================

plt.figure(figsize=(10, 7))

colors = ['#e74c3c','#3498db','#2ecc71','#f39c12','#9b59b6','#1abc9c']

for (name, res), color in zip(results.items(), colors):
    fpr, tpr, _ = roc_curve(y_test, res['y_prob'])
    plt.plot(fpr, tpr, label=f"{name} (AUC={res['AUC-ROC']:.3f})",
             color=color, linewidth=2)

plt.plot([0, 1], [0, 1], 'k--', linewidth=1.5, label='Random Classifier')
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curves — All Models', fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=10)
plt.grid(True, alpha=0.4)
plt.tight_layout()
plt.savefig('roc_curves.png', dpi=150, bbox_inches='tight')
plt.show()

# ========================================================
# CELL 13: Best Model — Confusion Matrix & Classification Report
# ========================================================

best = results[best_model_name]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Confusion Matrix
cm = confusion_matrix(y_test, best['y_pred'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Stay', 'Leave'])
disp.plot(ax=axes[0], colorbar=False, cmap='Blues')
axes[0].set_title(f'Confusion Matrix\n{best_model_name}', fontsize=13, fontweight='bold')

# Precision-Recall Curve
precision_vals, recall_vals, _ = precision_recall_curve(y_test, best['y_prob'])
axes[1].plot(recall_vals, precision_vals, color='#e74c3c', linewidth=2)
axes[1].set_xlabel('Recall')
axes[1].set_ylabel('Precision')
axes[1].set_title(f'Precision-Recall Curve\n{best_model_name}', fontsize=13, fontweight='bold')
axes[1].grid(True, alpha=0.4)

plt.tight_layout()
plt.savefig('best_model_eval.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n📋 Classification Report — {best_model_name}")
print(classification_report(y_test, best['y_pred'], target_names=['Stay', 'Leave']))

# ========================================================
# CELL 14: Cross-Validation (Best Model)
# ========================================================

print(f"📊 5-Fold Stratified Cross-Validation — {best_model_name}")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

best_clf = results[best_model_name]['model']

# Use appropriate data
if best_model_name == 'Logistic Regression':
    Xc, yc = X_train_scaled, y_train_sm
else:
    Xc, yc = X_train_sm, y_train_sm

cv_scores = cross_val_score(best_clf, Xc, yc, cv=cv, scoring='roc_auc')

print(f"  AUC per fold: {[f'{s:.4f}' for s in cv_scores]}")
print(f"  Mean AUC   : {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# Plot CV scores
plt.figure(figsize=(8, 4))
plt.bar(range(1, 6), cv_scores, color='#3498db', edgecolor='black')
plt.axhline(cv_scores.mean(), color='red', linestyle='--', linewidth=2, label=f'Mean={cv_scores.mean():.3f}')
plt.xlabel('Fold')
plt.ylabel('AUC-ROC')
plt.title(f'Cross-Validation Scores — {best_model_name}', fontweight='bold')
plt.ylim(0, 1)
plt.legend()
plt.tight_layout()
plt.savefig('cross_validation.png', dpi=150, bbox_inches='tight')
plt.show()

# ========================================================
# CELL 15: Feature Importance (Random Forest / Tree-Based)
# ========================================================

# Use Random Forest for feature importance (reliable)
rf_model = results['Random Forest']['model']
feat_importance = pd.Series(rf_model.feature_importances_, index=X_train_sm.columns)
top_features = feat_importance.sort_values(ascending=False).head(20)

plt.figure(figsize=(10, 7))
colors_fi = plt.cm.RdYlGn_r(np.linspace(0, 1, len(top_features)))
top_features.plot(kind='barh', color=colors_fi, edgecolor='black')
plt.title('Top 20 Feature Importances (Random Forest)', fontsize=14, fontweight='bold')
plt.xlabel('Importance Score')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n🔑 Top 10 Attrition Predictors:")
for i, (feat, imp) in enumerate(top_features.head(10).items(), 1):
    print(f"  {i:2}. {feat:<35} {imp:.4f}")

# ========================================================
# CELL 16: SHAP Explainability (XAI) — Innovation Point
# ========================================================

print("Computing SHAP values (this may take ~30 seconds)...")

# Use XGBoost or Random Forest for SHAP
shap_model_name = 'XGBoost' if 'XGBoost' in results else 'Random Forest'
shap_clf = results[shap_model_name]['model']

# Sample for speed
X_shap_sample = X_test.sample(min(200, len(X_test)), random_state=42)

explainer = shap.TreeExplainer(shap_clf)
shap_values = explainer.shap_values(X_shap_sample)

# Handle multi-output (RF returns list)
if isinstance(shap_values, list):
    sv = shap_values[1]  # Class 1 = Attrition
else:
    sv = shap_values

# SHAP Summary Plot
plt.figure(figsize=(10, 7))
shap.summary_plot(sv, X_shap_sample, max_display=15, show=False)
plt.title(f'SHAP Summary Plot — {shap_model_name}\n(Impact on Attrition Prediction)',
          fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('shap_summary.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ SHAP explainability complete.")
print("\n📌 SHAP Interpretation: Red = feature pushes toward Attrition, Blue = pushes away")

# ========================================================
# CELL 17: Business Impact — Cost Savings Estimator
# ========================================================

print("=" * 60)
print("💼 BUSINESS IMPACT ANALYSIS")
print("=" * 60)

# Assumptions (industry standard)
total_employees = 1470
avg_annual_salary = 65000       # USD
replacement_cost_pct = 1.2      # 120% of annual salary
actual_attrition_rate = 0.16    # 16%
model_recall = results[best_model_name]['Recall']
model_precision = results[best_model_name]['Precision']
retention_success_rate = 0.30   # 30% of identified at-risk are retained

# Calculations
employees_leaving = int(total_employees * actual_attrition_rate)
cost_per_attrition = avg_annual_salary * replacement_cost_pct
total_attrition_cost = employees_leaving * cost_per_attrition

# With model intervention
detected_attritions = int(employees_leaving * model_recall)
retained_employees = int(detected_attritions * retention_success_rate)
cost_savings = retained_employees * cost_per_attrition

print(f"\n📊 Scenario: 1,470-employee company")
print(f"   Average Salary          : ${avg_annual_salary:,}")
print(f"   Replacement Cost        : ${cost_per_attrition:,.0f} (120% of salary)")
print(f"\n   Employees Leaving/Year  : {employees_leaving} ({actual_attrition_rate*100:.0f}%)")
print(f"   Total Attrition Cost    : ${total_attrition_cost:,.0f}")
print(f"\n   Model Recall            : {model_recall:.1%}")
print(f"   Employees Detected      : {detected_attritions}")
print(f"   Retention Success Rate  : {retention_success_rate:.0%}")
print(f"   Employees Retained      : {retained_employees}")
print(f"\n   💰 Estimated Cost Savings: ${cost_savings:,.0f} per year")
print(f"   📈 ROI of ML Model        : {(cost_savings/total_attrition_cost)*100:.1f}% cost reduction")

# ========================================================
# CELL 18: Risk Segmentation & HR Strategy
# ========================================================

# Risk scores for all test employees
risk_scores = best['y_prob']

risk_df = pd.DataFrame({
    'Risk_Score': risk_scores,
    'Actual': y_test.values,
})

# Segment
def risk_label(score):
    if score >= 0.70: return 'High Risk 🔴'
    elif score >= 0.40: return 'Medium Risk 🟡'
    else: return 'Low Risk 🟢'

risk_df['Risk_Level'] = risk_df['Risk_Score'].apply(risk_label)

print("=" * 55)
print("🎯 EMPLOYEE RISK SEGMENTATION")
print("=" * 55)
print(risk_df['Risk_Level'].value_counts())

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Risk distribution
axes[0].hist(risk_scores, bins=30, color='#3498db', edgecolor='black', alpha=0.8)
axes[0].axvline(0.40, color='orange', linestyle='--', linewidth=2, label='Medium Risk')
axes[0].axvline(0.70, color='red', linestyle='--', linewidth=2, label='High Risk')
axes[0].set_xlabel('Attrition Probability')
axes[0].set_ylabel('Number of Employees')
axes[0].set_title('Risk Score Distribution', fontweight='bold')
axes[0].legend()

# Risk segment counts
risk_counts = risk_df['Risk_Level'].value_counts()
colors_risk = ['#e74c3c', '#f39c12', '#2ecc71']
axes[1].pie(risk_counts.values, labels=risk_counts.index, autopct='%1.0f%%',
            colors=colors_risk, startangle=90)
axes[1].set_title('Employee Risk Segments', fontweight='bold')

plt.suptitle('HR Risk Segmentation Dashboard', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('risk_segmentation.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📋 HR ACTION PLAN BY SEGMENT:")
print("  🔴 High Risk   → Immediate 1-on-1, salary review, flexible work options")
print("  🟡 Medium Risk → Career development plan, manager check-in, training")
print("  🟢 Low Risk    → Recognition programs, maintain engagement")

# ========================================================
# CELL 19: Fairness & Bias Analysis
# ========================================================

print("=" * 60)
print("⚖️  ETHICS, FAIRNESS & GOVERNANCE ANALYSIS")
print("=" * 60)

# Check if Gender column exists (encoded as 0/1)
gender_col = 'Gender' if 'Gender' in X_test.columns else None

if gender_col:
    test_copy = X_test.copy()
    test_copy['Actual'] = y_test.values
    test_copy['Predicted'] = best['y_pred']
    test_copy['Risk_Score'] = best['y_prob']

    groups = {1: 'Male', 0: 'Female'}
    print("\n📊 Model Performance by Gender Group:")
    print("-" * 50)
    for g_val, g_name in groups.items():
        sub = test_copy[test_copy['Gender'] == g_val]
        if len(sub) > 0 and sub['Actual'].nunique() > 1:
            acc_g = accuracy_score(sub['Actual'], sub['Predicted'])
            rec_g = recall_score(sub['Actual'], sub['Predicted'])
            f1_g  = f1_score(sub['Actual'], sub['Predicted'])
            print(f"  {g_name:<10} | n={len(sub):4d} | Acc={acc_g:.3f} | Recall={rec_g:.3f} | F1={f1_g:.3f}")

print("\n🔒 ETHICAL PRINCIPLES FOLLOWED IN THIS MODEL:")
ethics = [
    ("Transparency",    "SHAP values used to explain individual predictions"),
    ("Fairness",        "Model performance evaluated across Gender groups"),
    ("Privacy",         "Employee IDs removed; no PII used in model"),
    ("Accountability",  "HR remains decision-maker; model is advisory only"),
    ("Non-Automation",  "Model flags risk, human reviews before any action"),
    ("Consent",         "Employees should be informed data is used for HR analytics"),
    ("Bias Mitigation", "SMOTE prevents majority-class bias; fairness metrics monitored"),
]
for principle, description in ethics:
    print(f"  ✅ {principle:<20}: {description}")

# ========================================================
# CELL 20: Decision Tree Visualization (Interpretability)
# ========================================================

dt_model = results['Decision Tree']['model']
feature_names = X_train_sm.columns.tolist()

plt.figure(figsize=(20, 10))
plot_tree(dt_model,
          feature_names=feature_names,
          class_names=['Stay', 'Leave'],
          filled=True,
          max_depth=3,
          fontsize=9,
          impurity=False,
          rounded=True)
plt.title('Decision Tree (Depth=3) — Interpretable Attrition Rules',
          fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('decision_tree.png', dpi=100, bbox_inches='tight')
plt.show()
print("✅ Decision tree shows interpretable business rules")

# ========================================================
# CELL 21: Interactive Employee Attrition Predictor
# ========================================================

def predict_attrition(employee_data: dict) -> dict:
    """
    Predicts attrition risk for a given employee.
    employee_data: dict of feature values
    Returns: dict with risk score, label, and recommendation
    """
    # Create a row matching training features
    emp_df = pd.DataFrame([employee_data])

    # Encode Gender and OverTime
    if 'Gender' in emp_df.columns:
        emp_df['Gender'] = emp_df['Gender'].map({'Male': 1, 'Female': 0}).fillna(0)
    if 'OverTime' in emp_df.columns:
        emp_df['OverTime'] = emp_df['OverTime'].map({'Yes': 1, 'No': 0}).fillna(0)

    # One-hot encode categoricals
    emp_df = pd.get_dummies(emp_df)

    # Align columns with training data
    emp_df = emp_df.reindex(columns=X_train_sm.columns, fill_value=0)

    # Predict
    clf = results[best_model_name]['model']
    prob = clf.predict_proba(emp_df)[0][1]
    pred = clf.predict(emp_df)[0]

    if prob >= 0.70:
        risk = "🔴 HIGH RISK"
        action = "Immediate 1:1 meeting, compensation review, explore flexible work"
    elif prob >= 0.40:
        risk = "🟡 MEDIUM RISK"
        action = "Career development plan, training opportunities, manager check-in"
    else:
        risk = "🟢 LOW RISK"
        action = "Maintain engagement with recognition and growth opportunities"

    return {
        'Attrition Probability': f"{prob:.1%}",
        'Prediction': 'Will Leave' if pred == 1 else 'Will Stay',
        'Risk Level': risk,
        'Recommended HR Action': action
    }


# -------------------------------------------------------
# TEST CASE 1: High-Risk Employee Profile
# -------------------------------------------------------
employee_high_risk = {
    'Age': 27,
    'Gender': 'Male',
    'MaritalStatus': 'Single',
    'Department': 'Sales',
    'JobLevel': 1,
    'MonthlyIncome': 2500,
    'JobSatisfaction': 1,
    'EnvironmentSatisfaction': 1,
    'WorkLifeBalance': 1,
    'OverTime': 'Yes',
    'YearsAtCompany': 1,
    'YearsSinceLastPromotion': 0,
    'TotalWorkingYears': 2,
    'DistanceFromHome': 25,
    'StockOptionLevel': 0,
    'JobInvolvement': 1,
}

result_hr = predict_attrition(employee_high_risk)
print("=" * 55)
print("👤 EMPLOYEE PROFILE 1 — Expected: High Risk")
print("=" * 55)
for k, v in employee_high_risk.items():
    print(f"  {k:<30}: {v}")
print()
print("📊 PREDICTION RESULT:")
for k, v in result_hr.items():
    print(f"  {k:<30}: {v}")

# -------------------------------------------------------
# TEST CASE 2: Low-Risk Employee Profile
# -------------------------------------------------------
employee_low_risk = {
    'Age': 42,
    'Gender': 'Female',
    'MaritalStatus': 'Married',
    'Department': 'R&D',
    'JobLevel': 4,
    'MonthlyIncome': 15000,
    'JobSatisfaction': 4,
    'EnvironmentSatisfaction': 4,
    'WorkLifeBalance': 3,
    'OverTime': 'No',
    'YearsAtCompany': 12,
    'YearsSinceLastPromotion': 1,
    'TotalWorkingYears': 18,
    'DistanceFromHome': 3,
    'StockOptionLevel': 3,
    'JobInvolvement': 4,
}

# -------------------------------------------------------
# TEST CASE 2: Low-Risk Employee Profile
# -------------------------------------------------------
employee_low_risk = {
    'Age': 42,
    'Gender': 'Female',
    'MaritalStatus': 'Married',
    'Department': 'R&D',
    'JobLevel': 4,
    'MonthlyIncome': 15000,
    'JobSatisfaction': 4,
    'EnvironmentSatisfaction': 4,
    'WorkLifeBalance': 3,
    'OverTime': 'No',
    'YearsAtCompany': 12,
    'YearsSinceLastPromotion': 1,
    'TotalWorkingYears': 18,
    'DistanceFromHome': 3,
    'StockOptionLevel': 3,
    'JobInvolvement': 4,
}

result_lr = predict_attrition(employee_low_risk)
print("=" * 55)
print("👤 EMPLOYEE PROFILE 2 — Expected: Low Risk")
print("=" * 55)
for k, v in employee_low_risk.items():
    print(f"  {k:<30}: {v}")
print()
print("📊 PREDICTION RESULT:")
for k, v in result_lr.items():
    print(f"  {k:<30}: {v}")

# ========================================================
# CELL 22: Bulk Prediction on New Employees
# ========================================================

# Predict on the full test set and show top at-risk employees
test_results_df = X_test.copy()
test_results_df['Actual_Attrition'] = y_test.values
test_results_df['Attrition_Probability'] = best['y_prob']
test_results_df['Risk_Level'] = test_results_df['Attrition_Probability'].apply(
    lambda x: '🔴 High' if x >= 0.70 else ('🟡 Medium' if x >= 0.40 else '🟢 Low')
)

# Top 10 highest-risk employees
print("🚨 TOP 10 HIGHEST ATTRITION RISK EMPLOYEES (from test set):")
top_at_risk = test_results_df.sort_values('Attrition_Probability', ascending=False).head(10)
display_cols = ['Attrition_Probability', 'Risk_Level', 'Actual_Attrition']

# Add MonthlyIncome and OverTime if available
for col in ['MonthlyIncome', 'OverTime', 'JobSatisfaction']:
    if col in top_at_risk.columns:
        display_cols.insert(-1, col)

print(top_at_risk[display_cols].to_string())

# ========================================================
# CELL 23: Final Summary Dashboard
# ========================================================

fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# 1. Attrition Rate
counts = df['Attrition'].value_counts()
axes[0,0].pie(counts.values, labels=counts.index, autopct='%1.1f%%',
              colors=['#2ecc71','#e74c3c'], startangle=90)
axes[0,0].set_title('Attrition Distribution', fontweight='bold')

# 2. Model Comparison (AUC)
model_names_short = [n.replace(' ', '\n') for n in results.keys()]
aucs = [results[n]['AUC-ROC'] for n in results.keys()]
bars = axes[0,1].bar(model_names_short, aucs, color=plt.cm.Set1(np.linspace(0, 1, len(aucs))),
                     edgecolor='black')
axes[0,1].set_title('AUC-ROC by Model', fontweight='bold')
axes[0,1].set_ylim(0, 1.1)
axes[0,1].set_ylabel('AUC-ROC')
for bar, auc in zip(bars, aucs):
    axes[0,1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                   f'{auc:.3f}', ha='center', fontsize=9)

# 3. Top Feature Importances
top10 = feat_importance.sort_values(ascending=False).head(10)
axes[0,2].barh(range(10), top10.values[::-1],
               color=plt.cm.RdYlGn_r(np.linspace(0, 1, 10)))
axes[0,2].set_yticks(range(10))
axes[0,2].set_yticklabels(top10.index[::-1], fontsize=9)
axes[0,2].set_title('Top 10 Attrition Drivers', fontweight='bold')

# 4. Confusion Matrix
cm = confusion_matrix(y_test, best['y_pred'])
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1,0],
            xticklabels=['Stay', 'Leave'], yticklabels=['Stay', 'Leave'])
axes[1,0].set_title(f'Confusion Matrix\n({best_model_name})', fontweight='bold')

# 5. Risk Segmentation
risk_counts = pd.cut(best['y_prob'], bins=[0, 0.4, 0.7, 1.0],
                     labels=['Low Risk', 'Medium Risk', 'High Risk']).value_counts()
axes[1,1].pie(risk_counts.values, labels=risk_counts.index, autopct='%1.0f%%',
              colors=['#2ecc71','#f39c12','#e74c3c'], startangle=90)
axes[1,1].set_title('Employee Risk Segments', fontweight='bold')

# 6. Business Impact
categories = ['Total\nAttrition Cost', 'Estimated\nSavings', 'Remaining\nCost']
values = [total_attrition_cost/1e6, cost_savings/1e6, (total_attrition_cost-cost_savings)/1e6]
colors_biz = ['#e74c3c', '#2ecc71', '#f39c12']
bars = axes[1,2].bar(categories, values, color=colors_biz, edgecolor='black')
axes[1,2].set_ylabel('USD (Millions)')
axes[1,2].set_title('Business Impact (Est.)', fontweight='bold')
for bar, val in zip(bars, values):
    axes[1,2].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                   f'${val:.2f}M', ha='center', fontweight='bold')

plt.suptitle('🏢 Employee Attrition Prediction — Project Summary Dashboard',
             fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('summary_dashboard.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Dashboard saved!")